window.esdocSearchIndex = [
  [
    "minimap/lib/mixins/canvas-drawer.js~canvasdrawer",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html",
    "<span>CanvasDrawer</span> <span class=\"search-result-import-path\">minimap/lib/mixins/canvas-drawer.js</span>",
    "class"
  ],
  [
    "minimap/lib/mixins/dom-styles-reader.js~domstylesreader",
    "class/lib/mixins/dom-styles-reader.js~DOMStylesReader.html",
    "<span>DOMStylesReader</span> <span class=\"search-result-import-path\">minimap/lib/mixins/dom-styles-reader.js</span>",
    "class"
  ],
  [
    "minimap/lib/decoration.js~decoration",
    "class/lib/decoration.js~Decoration.html",
    "<span>Decoration</span> <span class=\"search-result-import-path\">minimap/lib/decoration.js</span>",
    "class"
  ],
  [
    "minimap/lib/mixins/decoration-management.js~decorationmanagement",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html",
    "<span>DecorationManagement</span> <span class=\"search-result-import-path\">minimap/lib/mixins/decoration-management.js</span>",
    "class"
  ],
  [
    "minimap/lib/main.js~main",
    "class/lib/main.js~Main.html",
    "<span>Main</span> <span class=\"search-result-import-path\">minimap/lib/main.js</span>",
    "class"
  ],
  [
    "minimap/lib/minimap.js~minimap",
    "class/lib/minimap.js~Minimap.html",
    "<span>Minimap</span> <span class=\"search-result-import-path\">minimap/lib/minimap.js</span>",
    "class"
  ],
  [
    "minimap/lib/minimap-element.js~minimapelement",
    "class/lib/minimap-element.js~MinimapElement.html",
    "<span>MinimapElement</span> <span class=\"search-result-import-path\">minimap/lib/minimap-element.js</span>",
    "class"
  ],
  [
    "minimap/lib/mixins/plugin-management.js~pluginmanagement",
    "class/lib/mixins/plugin-management.js~PluginManagement.html",
    "<span>PluginManagement</span> <span class=\"search-result-import-path\">minimap/lib/mixins/plugin-management.js</span>",
    "class"
  ],
  [
    "minimap/lib/decorators/element.js~element",
    "function/index.html#static-function-element",
    "<span>element</span> <span class=\"search-result-import-path\">minimap/lib/decorators/element.js</span>",
    "function"
  ],
  [
    "minimap/lib/decorators/include.js~include",
    "function/index.html#static-function-include",
    "<span>include</span> <span class=\"search-result-import-path\">minimap/lib/decorators/include.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/adapters/legacy-adapter.js",
    "file/lib/adapters/legacy-adapter.js.html",
    "lib/adapters/legacy-adapter.js",
    "file"
  ],
  [
    "lib/adapters/stable-adapter.js",
    "file/lib/adapters/stable-adapter.js.html",
    "lib/adapters/stable-adapter.js",
    "file"
  ],
  [
    "lib/canvas-layer.js",
    "file/lib/canvas-layer.js.html",
    "lib/canvas-layer.js",
    "file"
  ],
  [
    "lib/decoration.js",
    "file/lib/decoration.js.html",
    "lib/decoration.js",
    "file"
  ],
  [
    "lib/decoration.js~decoration#constructor",
    "class/lib/decoration.js~Decoration.html#instance-constructor-constructor",
    "lib/decoration.js~Decoration#constructor",
    "method"
  ],
  [
    "lib/decoration.js~decoration#destroy",
    "class/lib/decoration.js~Decoration.html#instance-method-destroy",
    "lib/decoration.js~Decoration#destroy",
    "method"
  ],
  [
    "lib/decoration.js~decoration#getid",
    "class/lib/decoration.js~Decoration.html#instance-method-getId",
    "lib/decoration.js~Decoration#getId",
    "method"
  ],
  [
    "lib/decoration.js~decoration#getmarker",
    "class/lib/decoration.js~Decoration.html#instance-method-getMarker",
    "lib/decoration.js~Decoration#getMarker",
    "method"
  ],
  [
    "lib/decoration.js~decoration#getproperties",
    "class/lib/decoration.js~Decoration.html#instance-method-getProperties",
    "lib/decoration.js~Decoration#getProperties",
    "method"
  ],
  [
    "lib/decoration.js~decoration#isdestroyed",
    "class/lib/decoration.js~Decoration.html#instance-method-isDestroyed",
    "lib/decoration.js~Decoration#isDestroyed",
    "method"
  ],
  [
    "lib/decoration.js~decoration#istype",
    "class/lib/decoration.js~Decoration.html#instance-method-isType",
    "lib/decoration.js~Decoration#isType",
    "method"
  ],
  [
    "lib/decoration.js~decoration#ondidchangeproperties",
    "class/lib/decoration.js~Decoration.html#instance-method-onDidChangeProperties",
    "lib/decoration.js~Decoration#onDidChangeProperties",
    "method"
  ],
  [
    "lib/decoration.js~decoration#ondiddestroy",
    "class/lib/decoration.js~Decoration.html#instance-method-onDidDestroy",
    "lib/decoration.js~Decoration#onDidDestroy",
    "method"
  ],
  [
    "lib/decoration.js~decoration#setproperties",
    "class/lib/decoration.js~Decoration.html#instance-method-setProperties",
    "lib/decoration.js~Decoration#setProperties",
    "method"
  ],
  [
    "lib/decoration.js~decoration.istype",
    "class/lib/decoration.js~Decoration.html#static-method-isType",
    "lib/decoration.js~Decoration.isType",
    "method"
  ],
  [
    "lib/decorators/element.js",
    "file/lib/decorators/element.js.html",
    "lib/decorators/element.js",
    "file"
  ],
  [
    "lib/decorators/include.js",
    "file/lib/decorators/include.js.html",
    "lib/decorators/include.js",
    "file"
  ],
  [
    "lib/main.js",
    "file/lib/main.js.html",
    "lib/main.js",
    "file"
  ],
  [
    "lib/main.js~main#activate",
    "class/lib/main.js~Main.html#instance-method-activate",
    "lib/main.js~Main#activate",
    "method"
  ],
  [
    "lib/main.js~main#deactivate",
    "class/lib/main.js~Main.html#instance-method-deactivate",
    "lib/main.js~Main#deactivate",
    "method"
  ],
  [
    "lib/main.js~main#generateplugin",
    "class/lib/main.js~Main.html#instance-method-generatePlugin",
    "lib/main.js~Main#generatePlugin",
    "method"
  ],
  [
    "lib/main.js~main#getactiveminimap",
    "class/lib/main.js~Main.html#instance-method-getActiveMinimap",
    "lib/main.js~Main#getActiveMinimap",
    "method"
  ],
  [
    "lib/main.js~main#minimapclass",
    "class/lib/main.js~Main.html#instance-method-minimapClass",
    "lib/main.js~Main#minimapClass",
    "method"
  ],
  [
    "lib/main.js~main#minimapforeditor",
    "class/lib/main.js~Main.html#instance-method-minimapForEditor",
    "lib/main.js~Main#minimapForEditor",
    "method"
  ],
  [
    "lib/main.js~main#minimapforeditorelement",
    "class/lib/main.js~Main.html#instance-method-minimapForEditorElement",
    "lib/main.js~Main#minimapForEditorElement",
    "method"
  ],
  [
    "lib/main.js~main#observeminimaps",
    "class/lib/main.js~Main.html#instance-method-observeMinimaps",
    "lib/main.js~Main#observeMinimaps",
    "method"
  ],
  [
    "lib/main.js~main#ondidactivate",
    "class/lib/main.js~Main.html#instance-method-onDidActivate",
    "lib/main.js~Main#onDidActivate",
    "method"
  ],
  [
    "lib/main.js~main#ondidactivateplugin",
    "class/lib/main.js~Main.html#instance-method-onDidActivatePlugin",
    "lib/main.js~Main#onDidActivatePlugin",
    "method"
  ],
  [
    "lib/main.js~main#ondidaddplugin",
    "class/lib/main.js~Main.html#instance-method-onDidAddPlugin",
    "lib/main.js~Main#onDidAddPlugin",
    "method"
  ],
  [
    "lib/main.js~main#ondidcreateminimap",
    "class/lib/main.js~Main.html#instance-method-onDidCreateMinimap",
    "lib/main.js~Main#onDidCreateMinimap",
    "method"
  ],
  [
    "lib/main.js~main#ondiddeactivate",
    "class/lib/main.js~Main.html#instance-method-onDidDeactivate",
    "lib/main.js~Main#onDidDeactivate",
    "method"
  ],
  [
    "lib/main.js~main#ondiddeactivateplugin",
    "class/lib/main.js~Main.html#instance-method-onDidDeactivatePlugin",
    "lib/main.js~Main#onDidDeactivatePlugin",
    "method"
  ],
  [
    "lib/main.js~main#ondidremoveplugin",
    "class/lib/main.js~Main.html#instance-method-onDidRemovePlugin",
    "lib/main.js~Main#onDidRemovePlugin",
    "method"
  ],
  [
    "lib/main.js~main#standaloneminimapforeditor",
    "class/lib/main.js~Main.html#instance-method-standAloneMinimapForEditor",
    "lib/main.js~Main#standAloneMinimapForEditor",
    "method"
  ],
  [
    "lib/main.js~main#toggle",
    "class/lib/main.js~Main.html#instance-method-toggle",
    "lib/main.js~Main#toggle",
    "method"
  ],
  [
    "lib/minimap-element.js",
    "file/lib/minimap-element.js.html",
    "lib/minimap-element.js",
    "file"
  ],
  [
    "lib/minimap-element.js~minimapelement#attach",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-attach",
    "lib/minimap-element.js~MinimapElement#attach",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#destroy",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-destroy",
    "lib/minimap-element.js~MinimapElement#destroy",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#detach",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-detach",
    "lib/minimap-element.js~MinimapElement#detach",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#getmodel",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-getModel",
    "lib/minimap-element.js~MinimapElement#getModel",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#gettexteditor",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-getTextEditor",
    "lib/minimap-element.js~MinimapElement#getTextEditor",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#gettexteditorelement",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-getTextEditorElement",
    "lib/minimap-element.js~MinimapElement#getTextEditorElement",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#gettexteditorelementroot",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-getTextEditorElementRoot",
    "lib/minimap-element.js~MinimapElement#getTextEditorElementRoot",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#isvisible",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-isVisible",
    "lib/minimap-element.js~MinimapElement#isVisible",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#requestforcedupdate",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-requestForcedUpdate",
    "lib/minimap-element.js~MinimapElement#requestForcedUpdate",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#requestupdate",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-requestUpdate",
    "lib/minimap-element.js~MinimapElement#requestUpdate",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#setdisplaycodehighlights",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-setDisplayCodeHighlights",
    "lib/minimap-element.js~MinimapElement#setDisplayCodeHighlights",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#setmodel",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-setModel",
    "lib/minimap-element.js~MinimapElement#setModel",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement#setstandalone",
    "class/lib/minimap-element.js~MinimapElement.html#instance-method-setStandAlone",
    "lib/minimap-element.js~MinimapElement#setStandAlone",
    "method"
  ],
  [
    "lib/minimap-element.js~minimapelement.registerviewprovider",
    "class/lib/minimap-element.js~MinimapElement.html#static-method-registerViewProvider",
    "lib/minimap-element.js~MinimapElement.registerViewProvider",
    "method"
  ],
  [
    "lib/minimap-plugin-generator-element.js",
    "file/lib/minimap-plugin-generator-element.js.html",
    "lib/minimap-plugin-generator-element.js",
    "file"
  ],
  [
    "lib/minimap-quick-settings-element.js",
    "file/lib/minimap-quick-settings-element.js.html",
    "lib/minimap-quick-settings-element.js",
    "file"
  ],
  [
    "lib/minimap.js",
    "file/lib/minimap.js.html",
    "lib/minimap.js",
    "file"
  ],
  [
    "lib/minimap.js~minimap#canscroll",
    "class/lib/minimap.js~Minimap.html#instance-method-canScroll",
    "lib/minimap.js~Minimap#canScroll",
    "method"
  ],
  [
    "lib/minimap.js~minimap#constructor",
    "class/lib/minimap.js~Minimap.html#instance-constructor-constructor",
    "lib/minimap.js~Minimap#constructor",
    "method"
  ],
  [
    "lib/minimap.js~minimap#destroy",
    "class/lib/minimap.js~Minimap.html#instance-method-destroy",
    "lib/minimap.js~Minimap#destroy",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getcapedtexteditorscrollratio",
    "class/lib/minimap.js~Minimap.html#instance-method-getCapedTextEditorScrollRatio",
    "lib/minimap.js~Minimap#getCapedTextEditorScrollRatio",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getcharheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getCharHeight",
    "lib/minimap.js~Minimap#getCharHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getcharwidth",
    "class/lib/minimap.js~Minimap.html#instance-method-getCharWidth",
    "lib/minimap.js~Minimap#getCharWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getfirstvisiblescreenrow",
    "class/lib/minimap.js~Minimap.html#instance-method-getFirstVisibleScreenRow",
    "lib/minimap.js~Minimap#getFirstVisibleScreenRow",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getHeight",
    "lib/minimap.js~Minimap#getHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gethorizontalscalefactor",
    "class/lib/minimap.js~Minimap.html#instance-method-getHorizontalScaleFactor",
    "lib/minimap.js~Minimap#getHorizontalScaleFactor",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getinterline",
    "class/lib/minimap.js~Minimap.html#instance-method-getInterline",
    "lib/minimap.js~Minimap#getInterline",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getlastvisiblescreenrow",
    "class/lib/minimap.js~Minimap.html#instance-method-getLastVisibleScreenRow",
    "lib/minimap.js~Minimap#getLastVisibleScreenRow",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getlineheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getLineHeight",
    "lib/minimap.js~Minimap#getLineHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getmaxscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-getMaxScrollTop",
    "lib/minimap.js~Minimap#getMaxScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getscreenheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getScreenHeight",
    "lib/minimap.js~Minimap#getScreenHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getscreenwidth",
    "class/lib/minimap.js~Minimap.html#instance-method-getScreenWidth",
    "lib/minimap.js~Minimap#getScreenWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-getScrollTop",
    "lib/minimap.js~Minimap#getScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditor",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditor",
    "lib/minimap.js~Minimap#getTextEditor",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorHeight",
    "lib/minimap.js~Minimap#getTextEditorHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditormaxscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorMaxScrollTop",
    "lib/minimap.js~Minimap#getTextEditorMaxScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscaledheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScaledHeight",
    "lib/minimap.js~Minimap#getTextEditorScaledHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscaledscrollleft",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScaledScrollLeft",
    "lib/minimap.js~Minimap#getTextEditorScaledScrollLeft",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscaledscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScaledScrollTop",
    "lib/minimap.js~Minimap#getTextEditorScaledScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscrollleft",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScrollLeft",
    "lib/minimap.js~Minimap#getTextEditorScrollLeft",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscrollratio",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScrollRatio",
    "lib/minimap.js~Minimap#getTextEditorScrollRatio",
    "method"
  ],
  [
    "lib/minimap.js~minimap#gettexteditorscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-getTextEditorScrollTop",
    "lib/minimap.js~Minimap#getTextEditorScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getverticalscalefactor",
    "class/lib/minimap.js~Minimap.html#instance-method-getVerticalScaleFactor",
    "lib/minimap.js~Minimap#getVerticalScaleFactor",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getvisibleheight",
    "class/lib/minimap.js~Minimap.html#instance-method-getVisibleHeight",
    "lib/minimap.js~Minimap#getVisibleHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getvisiblewidth",
    "class/lib/minimap.js~Minimap.html#instance-method-getVisibleWidth",
    "lib/minimap.js~Minimap#getVisibleWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#getwidth",
    "class/lib/minimap.js~Minimap.html#instance-method-getWidth",
    "lib/minimap.js~Minimap#getWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#isdestroyed",
    "class/lib/minimap.js~Minimap.html#instance-method-isDestroyed",
    "lib/minimap.js~Minimap#isDestroyed",
    "method"
  ],
  [
    "lib/minimap.js~minimap#isstandalone",
    "class/lib/minimap.js~Minimap.html#instance-method-isStandAlone",
    "lib/minimap.js~Minimap#isStandAlone",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondidchange",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidChange",
    "lib/minimap.js~Minimap#onDidChange",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondidchangeconfig",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidChangeConfig",
    "lib/minimap.js~Minimap#onDidChangeConfig",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondidchangescrollleft",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidChangeScrollLeft",
    "lib/minimap.js~Minimap#onDidChangeScrollLeft",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondidchangescrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidChangeScrollTop",
    "lib/minimap.js~Minimap#onDidChangeScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondidchangestandalone",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidChangeStandAlone",
    "lib/minimap.js~Minimap#onDidChangeStandAlone",
    "method"
  ],
  [
    "lib/minimap.js~minimap#ondiddestroy",
    "class/lib/minimap.js~Minimap.html#instance-method-onDidDestroy",
    "lib/minimap.js~Minimap#onDidDestroy",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setcharheight",
    "class/lib/minimap.js~Minimap.html#instance-method-setCharHeight",
    "lib/minimap.js~Minimap#setCharHeight",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setcharwidth",
    "class/lib/minimap.js~Minimap.html#instance-method-setCharWidth",
    "lib/minimap.js~Minimap#setCharWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setinterline",
    "class/lib/minimap.js~Minimap.html#instance-method-setInterline",
    "lib/minimap.js~Minimap#setInterline",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setscreenheightandwidth",
    "class/lib/minimap.js~Minimap.html#instance-method-setScreenHeightAndWidth",
    "lib/minimap.js~Minimap#setScreenHeightAndWidth",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-setScrollTop",
    "lib/minimap.js~Minimap#setScrollTop",
    "method"
  ],
  [
    "lib/minimap.js~minimap#setstandalone",
    "class/lib/minimap.js~Minimap.html#instance-method-setStandAlone",
    "lib/minimap.js~Minimap#setStandAlone",
    "method"
  ],
  [
    "lib/minimap.js~minimap#settexteditorscrolltop",
    "class/lib/minimap.js~Minimap.html#instance-method-setTextEditorScrollTop",
    "lib/minimap.js~Minimap#setTextEditorScrollTop",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js",
    "file/lib/mixins/canvas-drawer.js.html",
    "lib/mixins/canvas-drawer.js",
    "file"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#backlayer",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-member-backLayer",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#backLayer",
    "member"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#frontlayer",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-member-frontLayer",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#frontLayer",
    "member"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#getdecorationcolor",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-getDecorationColor",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#getDecorationColor",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#getdefaultcolor",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-getDefaultColor",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#getDefaultColor",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#getfrontcanvas",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-getFrontCanvas",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#getFrontCanvas",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#gettextopacity",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-getTextOpacity",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#getTextOpacity",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#gettokencolor",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-getTokenColor",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#getTokenColor",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#initializecanvas",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-initializeCanvas",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#initializeCanvas",
    "method"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#tokenslayer",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-member-tokensLayer",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#tokensLayer",
    "member"
  ],
  [
    "lib/mixins/canvas-drawer.js~canvasdrawer#updatecanvas",
    "class/lib/mixins/canvas-drawer.js~CanvasDrawer.html#instance-method-updateCanvas",
    "lib/mixins/canvas-drawer.js~CanvasDrawer#updateCanvas",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js",
    "file/lib/mixins/decoration-management.js.html",
    "lib/mixins/decoration-management.js",
    "file"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#decoratemarker",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-decorateMarker",
    "lib/mixins/decoration-management.js~DecorationManagement#decorateMarker",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#decorationforid",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-decorationForId",
    "lib/mixins/decoration-management.js~DecorationManagement#decorationForId",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#decorationsbytypethenrows",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-decorationsByTypeThenRows",
    "lib/mixins/decoration-management.js~DecorationManagement#decorationsByTypeThenRows",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#decorationsforscreenrowrange",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-decorationsForScreenRowRange",
    "lib/mixins/decoration-management.js~DecorationManagement#decorationsForScreenRowRange",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#getdecorations",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-getDecorations",
    "lib/mixins/decoration-management.js~DecorationManagement#getDecorations",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#initializedecorations",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-initializeDecorations",
    "lib/mixins/decoration-management.js~DecorationManagement#initializeDecorations",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#invalidatedecorationforscreenrowscache",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-invalidateDecorationForScreenRowsCache",
    "lib/mixins/decoration-management.js~DecorationManagement#invalidateDecorationForScreenRowsCache",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#ondidadddecoration",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-onDidAddDecoration",
    "lib/mixins/decoration-management.js~DecorationManagement#onDidAddDecoration",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#ondidchangedecoration",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-onDidChangeDecoration",
    "lib/mixins/decoration-management.js~DecorationManagement#onDidChangeDecoration",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#ondidchangedecorationrange",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-onDidChangeDecorationRange",
    "lib/mixins/decoration-management.js~DecorationManagement#onDidChangeDecorationRange",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#ondidremovedecoration",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-onDidRemoveDecoration",
    "lib/mixins/decoration-management.js~DecorationManagement#onDidRemoveDecoration",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#ondidupdatedecoration",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-onDidUpdateDecoration",
    "lib/mixins/decoration-management.js~DecorationManagement#onDidUpdateDecoration",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#removealldecorations",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-removeAllDecorations",
    "lib/mixins/decoration-management.js~DecorationManagement#removeAllDecorations",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#removealldecorationsformarker",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-removeAllDecorationsForMarker",
    "lib/mixins/decoration-management.js~DecorationManagement#removeAllDecorationsForMarker",
    "method"
  ],
  [
    "lib/mixins/decoration-management.js~decorationmanagement#removedecoration",
    "class/lib/mixins/decoration-management.js~DecorationManagement.html#instance-method-removeDecoration",
    "lib/mixins/decoration-management.js~DecorationManagement#removeDecoration",
    "method"
  ],
  [
    "lib/mixins/dom-styles-reader.js",
    "file/lib/mixins/dom-styles-reader.js.html",
    "lib/mixins/dom-styles-reader.js",
    "file"
  ],
  [
    "lib/mixins/dom-styles-reader.js~domstylesreader#invalidatedomstylescache",
    "class/lib/mixins/dom-styles-reader.js~DOMStylesReader.html#instance-method-invalidateDOMStylesCache",
    "lib/mixins/dom-styles-reader.js~DOMStylesReader#invalidateDOMStylesCache",
    "method"
  ],
  [
    "lib/mixins/dom-styles-reader.js~domstylesreader#retrievestylefromdom",
    "class/lib/mixins/dom-styles-reader.js~DOMStylesReader.html#instance-method-retrieveStyleFromDom",
    "lib/mixins/dom-styles-reader.js~DOMStylesReader#retrieveStyleFromDom",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js",
    "file/lib/mixins/plugin-management.js.html",
    "lib/mixins/plugin-management.js",
    "file"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#deactivateallplugins",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-deactivateAllPlugins",
    "lib/mixins/plugin-management.js~PluginManagement#deactivateAllPlugins",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#eachplugin",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-eachPlugin",
    "lib/mixins/plugin-management.js~PluginManagement#eachPlugin",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#provideminimapservicev1",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-provideMinimapServiceV1",
    "lib/mixins/plugin-management.js~PluginManagement#provideMinimapServiceV1",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#registerplugin",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-registerPlugin",
    "lib/mixins/plugin-management.js~PluginManagement#registerPlugin",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#togglepluginactivation",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-togglePluginActivation",
    "lib/mixins/plugin-management.js~PluginManagement#togglePluginActivation",
    "method"
  ],
  [
    "lib/mixins/plugin-management.js~pluginmanagement#unregisterplugin",
    "class/lib/mixins/plugin-management.js~PluginManagement.html#instance-method-unregisterPlugin",
    "lib/mixins/plugin-management.js~PluginManagement#unregisterPlugin",
    "method"
  ]
]